[package]
name = "rusto_rusto"
version = "0.1.0"
authors = ["Toni Okuogume <tokuogume@gmail.com>"]

[dependencies]
ggez = { version = "0.3", features = ["cargo-resource-root"] }
rand = "0.3.15"
snowflake = "1.3.0"